### ISSUE TITLE
Tag Locker - Role Error

### ISSUE THREAD

**Issue by tiffanymullins** [zendesklabs/tag_locker_app#16]
Hello there,
 
I'm experiencing an issue with tagging our tickets with any of the tags we have in our Tag Locker database. Each time we try to add one to a ticket, the below message error pops up. It seems to be an issue for all user roles assigned and all tags seem to restricted at this point. We have made no changes on our end that would account for such an error. 

I've tried uninstalling and reinstalling but having the same error.
<img width="379" alt="screen shot 2016-08-30 at 12 46 59 pm" src="https://cloud.githubusercontent.com/assets/21340283/18098337/dcabda8c-6eaf-11e6-8520-3c758a9bc346.png">

I started seeing this issue August 25 (looks like it coincides with an update).

**Comment by epritchard** [comment]
Hi Tiffany,
Just following up here to tie up loose ends. The trouble you ran into was a result of the tags being entered into the app settings using new lines as a delimiter, rather than spaces. In the future, I may try to make the app a bit more robust so that it will look for either.

For now, I'll close this out.

Thank you,
Ed
