### ISSUE TITLE
Newly Added Tag Does Not Populate as Option

### ISSUE THREAD

**Issue by HPwES** [zendesklabs/tag_locker_app#20]
Hello - We newly added a few tags into the tag locker, however under the Organization and Ticket tag sections the tag does not auto populate nor does it let you add the tag.

**Comment by epritchard** [comment]
Hi HPwES,
Thanks for reaching out about this. I've taken a look at this possible issue in my copy of Tag Locker, and it appears that what you're seeing might actually be caused by the newly updated app's settings not having kicked in yet. If you refresh your browser, that should reload the app's new settings and reveal the newly added tags. Can you confirm if they still do not show up for you?

**Comment by HPwES** [comment]
Good morning Ed,

The tags appears this morning, so your suggestion was correct.  Thanks and have a great weekend!

Sarah

**Comment by epritchard** [comment]
Excellent! Happy to hear things are working for you. :)

I'll go ahead and close out this issue now.
