### ISSUE TITLE
non-admin users | tag additions don't save

### ISSUE THREAD

**Issue by bambora-bcameron** [zendesklabs/tag_locker_app#21]
I'm using 1.5.7 downloaded from the git repo and installed manually (I had the marketplace version installed but it auto-updated to a version with a bug a few months ago so I wanted a static/working version instead), but we're noticing that non-admin/staff level users can't add tags.  

During testing when I upgrade a staff user to admin they can manually add a tag via the app interface, but when at staff level even if they select a tag it doesn't submit.  Auto-tags via triggers/automation work fine, and admins can select and save tags at all times.

I do not have role restrictions enabled, and all tags are in available tags field and nothing in the restricted field, I even disabled the admin override and tested and it still works for an admin but no change for a staff level user.

**Comment by bambora-bcameron** [comment]
I tried using the marketplace version (which is also 1.5.7 but the notes only list up to 1.5.5) and same issue, it ignores tag additions by non-admin level users.

**Comment by epritchard** [comment]
Hello @bambora-bcameron,
I have tested and confirmed that my staff-level users are able to add tags through the app (marketplace version). I suspect that you have custom roles enabled on your Zendesk instance for your staff. Can you please check to see if the `Can edit ticket tags` permission is enabled on the role for those users? To clarify, this is _not_ an app setting, this is a system-wide setting for your staff level role.

Additionally, you mentioned that there was a bug introduced at some point with the marketplace version. Can you please elaborate on whether the bug still exists and what it was? If there is an ongoing issue, I would love to know about it.

Thank you kindly,
Ed

**Comment by bambora-bcameron** [comment]
It does appear that may have been the issue, although we're using the supplied standard roles (admin, staff, etc) and haven't done any custom roles.  This was also working fine for almost a year until September (I think that's when there was a bug that popped up), and then again after that point, I suspect one of the other admins on our side changed this permission without me knowing it :(


There should be a set of requirements in the config text for the app, maybe a warning about the permission being required for roles that have access to the app?


Thanks!

________________________________

**Comment by epritchard** [comment]
Hi @bambora-bcameron,
Thanks for clarifying what was happening, and I'm happy to hear that this was just a role permission issue instead of a bug. Not too long ago I made an enhancement to the app to check if the app is running in a misconfigured environment (e.g. the tags have been disabled on the system), but the way it is handled still allows for some misconfigurations to slip by without the app knowing it (e.g. the role doesn't have the ability to add/edit tags on tickets). 

I'm going to create a new "enhancement" issue on the repo to look at ways of improving these checks in the future.  Additionally, I agree that it would be best if these requirements are called out in the app's description/instructions. So, I will add an enhancement issue for improving the documentation, as well.

For now, I will close this issue out. If you have any further trouble, please let me know.

Thank you,
Ed
